networks:
  exmpltask_network:
    external: true

name: exmpl-task-docker

services:
  app:
    image: nginx:latest
    container_name: exmpl-task-app
    ports:
      - "8812:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - exmpltask_network
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      - exmpltask_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-exmpl
    restart: unless-stopped
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: exmpltask
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - exmpltask_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dbdata: